###
POST http://localhost:3000/teams 
Content-Type: application/json

    {
    "Team ID": "T090",
    "Team Name": "Suits",
    "Location": "Mikes Office",
    "Founded Year": "2003",
    "Coach ID": "C005"
  }

####
POST http://localhost:3000/players
Content-Type: application/json

{
    "Name": "Can't touch this",
    "Age": "55",
    "Height": "8ft 6in",
    "Nationality": "Mine Precious",
    "Position": "Defense",
    "Team Id": "901",
    "Player ID": 88
  }